### ISSUE TITLE
[1.1.1] SMP GUI failure

### ISSUE THREAD

**Issue by Tokeli** [ldtteam/Piston-Unlimited#1]
Forge: 14.23.4.2760
Multi-Piston: 1.1.1

Block works fine in SSP, but in SMP the UI fails!

Log: https://pastebin.com/d4d9QTa1

**Comment by Raycoms** [comment]
Thanks for reporting this, we'll check it out right away

**Comment by Jergeric** [comment]
Forge: 14.23.5.2770

We also have the same problem on our server

https://pastebin.com/0XWxM6ND

**Comment by OrionDevelopment** [comment]
I tested it in my smp dev world their it works

**Comment by OrionDevelopment** [comment]
Might be something with the obfuscation go arway, debugging iy

**Comment by Jergeric** [comment]
Can I help with certain information or logs?

**Comment by OrionDevelopment** [comment]
So I dug up the issue. Turns out the Loader hat a bug when the json file is zipped.

I fixed that, but found a bug in the text field which I will now need to fix.
