### ISSUE TITLE
Game crash when turning on piston (only with solid blocks)

### ISSUE THREAD

**Issue by giggity404** [ldtteam/Piston-Unlimited#15]
My game crashes when I try to make the piston move blocks, it seems to work with fences, however as soon as i replace the fences with solid blocks, and try to turn it on, the game crashes.
When I reload the game, a single block appears has moved past the multipiston, however all the original blocks are still in place. (so i get an extra block, could be a good dupe)
(This error in particular was for honeyblock but i tried with stone and glass aswell)

Forge:  31.2.8
Structurize:  0.10.322

Error:
The game crashed whilst ticking block entity
Error: java.lang.ClassCastException: net.minecraft.block.HoneyBlock cannot be cast to net.minecraft.block.IBucketPickupHandler

Crash report:
https://pastebin.com/vncPeaZb

**Comment by Raycoms** [comment]
fixed
