### ISSUE TITLE
Multi-Piston breaking doesn't drop the block

### ISSUE THREAD

**Issue by VolcanicMG** [ldtteam/Piston-Unlimited#17]
I'm playing on a forge server and whenever I break the multi-piston it wont give back the block. I don't believe this is intentional and if it is, this should be changed.

**Comment by Divineaspect** [comment]
still true on 1.18.2

**Comment by Raycoms** [comment]
pushing out updates

**Comment by lI-guy-Il** [comment]
@Raycoms this still is an issue on my server. Here is the version I have installed: 

![Image](https://github.com/user-attachments/assets/e52c2c38-49ea-4594-9b05-ee237a0d3299)

**Comment by Raycoms** [comment]
Released update with fix
