### ISSUE TITLE
No Buttons nor Lever

### ISSUE THREAD

**Issue by ObiGanovi** [ldtteam/Piston-Unlimited#18]
I cannot attach a button or lever directly to the multi-piston, neither with Shift+LMB nor otherwise. Has the function been removed?
Forge 40.1.57
Minecraft 1.18.2
Mod versions:
multi-piston-1.18.2-1.2.13-ALPHA (1).jar
blockui-1.18.2-0.0.58-ALPHA.jar
structurize-1.18.2-1.0.411-ALPHA.jar

Logs: https://gist.github.com/ObiGanovi/7abb4c469330e4db9c85f98bfb24e204

![2022-07-28_18 44 26](https://user-images.githubusercontent.com/104677828/181592979-6bb9c1c7-47f9-4598-8ee2-86dff2818444.png)

**Comment by Raycoms** [comment]
Merged some stuff for that

**Comment by ObiGanovi** [comment]
uuuuh nice. thanks for the update :D
