### ISSUE TITLE
Server crash on startup - Error during loading

### ISSUE THREAD

**Issue by Pandaw15** [ldtteam/Piston-Unlimited#19]
So I updated the mod to 1.2.15, and after my server didn't restart after the auto restart, I checked the console/logs and the mod didn't load correctly. Crash report and logs:

[crash-2022-08-10_00.01.28-fml.txt](https://github.com/ldtteam/Piston-Unlimited/files/9301251/crash-2022-08-10_00.01.28-fml.txt)
 
[2022-08-10-2.log](https://github.com/ldtteam/Piston-Unlimited/files/9301255/2022-08-10-2.log)

It did work for a few time and then this happened. I restarted manually and it was fine, so I guess it doesn't happen everytime, but still worth checking.

1.18.2 with Forge 40.1.67

**Comment by Raycoms** [comment]
Very very weird forge crash. Might be worth reporting there as well

**Comment by Pandaw15** [comment]
Report to Forge ?

**Comment by Raycoms** [comment]
yes

**Comment by Pandaw15** [comment]
Okay, will do thx

**Comment by Pandaw15** [comment]
![image](https://user-images.githubusercontent.com/82103549/183945005-1ef902c6-200e-47f3-a4c4-8d0bddd39469.png)
![image](https://user-images.githubusercontent.com/82103549/183945041-878a6484-6cd9-4016-9087-6332af989d27.png)

Here's where it's discussed if you want https://discord.com/channels/313125603924639766/437001959950778368/1006947271335759923

**Comment by Raycoms** [comment]
fixed
