### ISSUE TITLE
[Suggestion] Change UI to make it easier to tell difference between in/out.

### ISSUE THREAD

**Issue by Tokeli** [ldtteam/Piston-Unlimited#2]
In 1.1.1, you sort of have to just remember the mod's specific color choices or check the mod page to remember which color does what.

I propose either changing the colors, or just adding a string of text to the bottom to tell which one's which.

Immersive Engineering and Thermal Expansion (and probably some others) both use blue (in) and orange (out) as colors for their machine inputs, and I believe they'd be a little more intuitive.

**Comment by Raycoms** [comment]
fix
