### ISSUE TITLE
Redstone Signal Transmission

### ISSUE THREAD

**Issue by LordRelentless** [ldtteam/Piston-Unlimited#20]
Right now you really can't build large multipiston systems, like an elevator, because (at least as far as I can tell) they don't transmit redstone signal. Which means you have to have multiple relays right next to the multipistons for you to have a platform to raise, and this very much limits the size of the platform. If you want an elevator larger than 2x, such as a 3x3 you can't do it, as the middle piston doesn't receive a signal.

**Comment by Raycoms** [comment]
I fixed this on

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by LordRelentless** [comment]
Well I have the latest version and it doesn't work. I was forced to build a 2x6 platform as it wouldn't move the center pieces with more than that.

**Comment by Raycoms** [comment]
Are you on 1.19?

**Comment by LordRelentless** [comment]
Yes, 1.19.2 with the Minecolonies Official Server Modpack.

**Comment by Raycoms** [comment]
should be fixed now
