### ISSUE TITLE
[1.21.1} Mod depency is having an issue

### ISSUE THREAD

**Issue by Periam** [ldtteam/Piston-Unlimited#32]
After installing the mods and the requested dependencies the game does not launch since is request a different version of the depency

MC 1.21.1
neoforge-21.1.28
blockui-1.0.184-1.21.1-beta
domun_ornamentum-1.21.1-1.0.200-beta
jei-1.21.1-neoforge-19.11.0.128
l2library-3.0.2+2
multipiston-1.21-1.2.47-Beta
structurize-1.0.750-1.21.1

[crash-2024-08-27_10.30.47-fml.txt](https://github.com/user-attachments/files/16762864/crash-2024-08-27_10.30.47-fml.txt)

![image](https://github.com/user-attachments/assets/1c79516e-686d-4be7-9a8c-e6b6ecf1cc12)

**Comment by Nightenom** [comment]
This will be fixed hopefully this week, we're aware and fully working on it. Will close now

**Comment by Periam** [comment]
hey, it is happening the same with other mod
![image](https://github.com/user-attachments/assets/6d6178ec-2680-4baf-8769-9a8858337c4f)
