### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by conan1256** [ldtteam/Piston-Unlimited#4]
Getting a error using this mod

 

The game crashed whilst rendering screen
The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: No style has a resource with the given id: image:up

https://pastebin.com/xfaq7WtT

**Comment by Raycoms** [comment]
Which version are you using?

Am So., 4. Nov. 2018 um 21:56 Uhr schrieb conan1256 <
notifications@github.com>:

**Comment by Raycoms** [comment]
Oh sorry, just saw this is for piston unlimited.
@Orion what did change with Blockout for that?

Am So., 4. Nov. 2018 um 22:02 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by ate0ate** [comment]
I still get this error using the current version of multi-piston. I cannot use the block GUI at all.

**Comment by OrionDevelopment** [comment]
Yeah it is known.
Currently working on a rewrite, so that we can clean port it to 1.13

**Comment by InnuendoSA** [comment]
I have the same issue on my test server. Right click and server goes down. 
So my question is on the rewrite for 1.13 is, will you rewrite 1.12.2 too or are you just going 1.13?
I really like this mod and Im not planing on a 1.13 mod pack yet.

**Comment by Raycoms** [comment]
Yes, it will rewrite 1.12 too

Am Mo., 4. März 2019 um 09:04 Uhr schrieb InnuendoSA <
notifications@github.com>:

**Comment by Raycoms** [comment]
fix
